export const STATUS_COLORS: Record<string, string> = {
  'REGISTERED': 'bg-slate-100 text-slate-700 border-slate-200',
  'SCREENING_PENDING': 'bg-blue-50 text-blue-700 border-blue-200',
  'SCREENING_IN_PROGRESS': 'bg-blue-100 text-blue-800 border-blue-300',
  'DOCTOR_PENDING': 'bg-indigo-50 text-indigo-700 border-indigo-200',
  'DOCTOR_IN_PROGRESS': 'bg-indigo-100 text-indigo-800 border-indigo-300',
  'POST_DOCTOR_PENDING': 'bg-violet-50 text-violet-700 border-violet-200',
  'POST_DOCTOR_IN_PROGRESS': 'bg-violet-100 text-violet-800 border-violet-300',
  'PAYMENT_PENDING': 'bg-amber-50 text-amber-700 border-amber-200',
  'PAYMENT_IN_PROGRESS': 'bg-amber-100 text-amber-800 border-amber-300',
  'DISPENSE_PENDING': 'bg-orange-50 text-orange-700 border-orange-200',
  'DISPENSE_IN_PROGRESS': 'bg-orange-100 text-orange-800 border-orange-300',
  'INJECTION_PENDING': 'bg-sky-50 text-sky-700 border-sky-200',
  'INJECTION_IN_PROGRESS': 'bg-sky-100 text-sky-800 border-sky-300',
  'COMPLETED': 'bg-emerald-50 text-emerald-700 border-emerald-200',
  'VOID': 'bg-red-50 text-red-700 border-red-200',
};

export const STATUS_LABELS: Record<string, string> = {
  'REGISTERED': 'ลงทะเบียนแล้ว',
  'SCREENING_PENDING': 'รอซักประวัติ',
  'SCREENING_IN_PROGRESS': 'กำลังซักประวัติ',
  'DOCTOR_PENDING': 'รอพบแพทย์',
  'DOCTOR_IN_PROGRESS': 'กำลังตรวจ',
  'POST_DOCTOR_PENDING': 'รอพยาบาลหลังพบแพทย์',
  'POST_DOCTOR_IN_PROGRESS': 'กำลังตรวจสอบโดยพยาบาล',
  'PAYMENT_PENDING': 'รอชำระเงิน',
  'PAYMENT_IN_PROGRESS': 'กำลังชำระเงิน',
  'DISPENSE_PENDING': 'รอจัดยา',
  'DISPENSE_IN_PROGRESS': 'กำลังจัดยา',
  'INJECTION_PENDING': 'รอฉีดวัคซีน',
  'INJECTION_IN_PROGRESS': 'กำลังฉีดวัคซีน',
  'COMPLETED': 'เสร็จสิ้น',
  'VOID': 'ยกเลิกการรับบริการ',
};
